### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org/projects/flameshot/flameshot/)
for Flameshot/Flameshot.

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by TomasKukumberg** [comment]
There's a typo on line 639 (Should be "Maximálna" instead of "Maximálne"). I've already fixed it on the weblate but I'm not sure if a commit will appear here or if another PR will be made for the fix. Anyways, apart from that it's good :)

**Comment by TomasKukumberg** [comment]
Ok, i see another commit has been added :) So the typo is fixed now and it can be merged.

**Review by borgmanJeremy — APPROVED** [review]

**Comment by borgmanJeremy** [comment]
Thanks! Based on your experience is there any documentation needed explaining the translation process?

**Comment by TomasKukumberg** [comment]
Maybe i would just add a comment explaining that Weblate takes a while to make a PR, otherwise it's pretty straightforward :) @borgmanJeremy

**Pull request merged**
