### PR TITLE
fixed seg fault

### LINKED ISSUE #2830: segfault when `flameshot config`
### Flameshot Version

Flameshot v12.1.0 (bd3431a9)
Compiled with Qt 5.15.5

### Installation Type

User repository (AUR)

### Operating System type and version

5.15.53-1-MANJARO

### Description

After the new merges I get segfault when loading config:

```console
❯  flameshot config
flameshot: error: The configuration contains an error. Open configuration to resolve.
[1]    645628 segmentation fault (core dumped)  flameshot config

```

Interestingly enough, I can use `flameshot gui` just fine (with or without daemon. To me this indicates that there might be nothing wrong with the config nor there is anything wrong with validating the config (as `flameshot gui` works), but there is a segfault for when the config window is created.

<details>
<summary> My config </summary>

```ini
[General]
allowMultipleGuiInstances=true
buttons=@Variant(\0\0\0\x7f\0\0\0\vQList<int>\0\0\0\0\x13\0\0\0\0\0\0\0\x1\0\0\0\x2\0\0\0\x3\0\0\0\x4\0\0\0\x5\0\0\0\x6\0\0\0\x12\0\0\0\xf\0\0\0\x13\0\0\0\b\0\0\0\t\0\0\0\x10\0\0\0\n\0\0\0\v\0\0\0\r\0\0\0\x17\0\0\0\f\0\0\0\x11)
contrastOpacity=135
copyPathAfterSave=true
disabledTrayIcon=false
drawColor=#fa0164
drawFontSize=14
drawThickness=20
predefinedColorPaletteLarge=false
saveAsFileExtension=png
saveLastRegion=false
savePath=/home/mehrad/Pictures
savePathFixed=false
showMagnifier=false
showSelectionGeometry=5
showStartupLaunchMessage=true
startupLaunch=true
uiColor=#ff7300
undoLimit=100
uploadHistoryMax=0
useJpgForClipboard=false
userColors=picker, #800000, #ff0000, #ffff00, #00ff00, #008000, #00ffff, #0000ff, #ff00ff, #800080, #fa0164

[Shortcuts]
TYPE_ARROW=A
TYPE_CIRCLE=
TYPE_CIRCLECOUNT=
TYPE_COMMIT_CURRENT_TOOL=Ctrl+Return
TYPE_COPY=Ctrl+C
TYPE_DELETE_CURRENT_TOOL=Del
TYPE_DRAWER=D
TYPE_EXIT=Ctrl+Q
TYPE_IMAGEUPLOADER=
TYPE_MARKER=M
TYPE_MOVESELECTION=Ctrl+M
TYPE_MOVE_DOWN=Down
TYPE_MOVE_LEFT=Left
TYPE_MOVE_RIGHT=Right
TYPE_MOVE_UP=Up
TYPE_OPEN_APP=Ctrl+O
TYPE_PENCIL=
TYPE_PIN='
TYPE_PIXELATE=B
TYPE_RECTANGLE=R
TYPE_REDO=Ctrl+Shift+Z
TYPE_RESIZE_DOWN=Shift+Down
TYPE_RESIZE_LEFT=Shift+Left
TYPE_RESIZE_RIGHT=Shift+Right
TYPE_RESIZE_UP=Shift+Up
TYPE_SAVE=Ctrl+S
TYPE_SELECTION=S
TYPE_SELECTIONINDICATOR=
TYPE_SELECT_ALL=Ctrl+A
TYPE_SIZEDECREASE=-
TYPE_SIZEINCREASE=+
TYPE_TEXT=T
TYPE_TOGGLE_PANEL=Space
TYPE_UNDO=Ctrl+Z

```
</details>

### Steps to reproduce

1. use my config
2. use the bd3431a9
3. `flameshot config`
4. segfault...

### Screenshots or screen recordings

_No response_

### System Information

```console
❯  inxi --system --graphics --width=80
System:
  Host: precisiontower Kernel: 5.15.53-1-MANJARO arch: x86_64 bits: 64
    Desktop: KDE Plasma v: 5.24.6 Distro: Manjaro Linux
Graphics:
  Device-1: Intel CometLake-S GT2 [UHD Graphics 630] driver: i915 v: kernel
  Device-2: AMD Lexa XT [Radeon PRO WX 3200] driver: amdgpu v: kernel
  Display: x11 server: X.Org v: 21.1.3 driver: X: loaded: amdgpu,modesetting
    gpu: amdgpu resolution: 1: 1920x1080~60Hz 2: 1080x1920~60Hz
    3: 1080x1920~60Hz
  OpenGL: renderer: AMD Radeon Pro WX 3200 Series (polaris12 LLVM 14.0.6 DRM
    3.42 5.15.53-1-MANJARO)
    v: 4.6 Mesa 22.1.3

```

### PR DESCRIPTION
**Pull request by borgmanJeremy**
Closes #2830

### CODE REVIEW

**Comment by mmahmoudian** [comment]
if there was just one mismatched name, why didn't it complained and instead threw segfault? What I mean is that shouldn't it suppose to inform user about the error about "having an extra unrecognized" argument?

**Comment by borgmanJeremy** [comment]
@mmahmoudian the issue was that the pointer was not initialized:


<details>
  <summary>Address Sanitizer Details</summary>
  
```
❯ ./src/flameshot config
flameshot: error: The configuration contains an error. Open configuration to resolve.
AddressSanitizer:DEADLYSIGNAL
=================================================================
==35834==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x56341ee02693 bp 0x7fffcc934a40 sp 0x7fffcc934a20 T0)
==35834==The signal is caused by a READ memory access.
==35834==Hint: address points to the zero page.
    #0 0x56341ee02693 in ConfigHandler::value(QString const&) const /home/jeremy/github/flameshot/src/utils/confighandler.cpp:461
    #1 0x56341edb8f52 in ConfigHandler::copyURLAfterUpload() /home/jeremy/github/flameshot/src/../src/utils/confighandler.h:100
    #2 0x56341edb8f52 in GeneralConf::_updateComponents(bool) /home/jeremy/github/flameshot/src/config/generalconf.cpp:79
    #3 0x56341edbcab5 in GeneralConf::GeneralConf(QWidget*) /home/jeremy/github/flameshot/src/config/generalconf.cpp:69
    #4 0x56341ed98f8d in ConfigWindow::ConfigWindow(QWidget*) /home/jeremy/github/flameshot/src/config/configwindow.cpp:72
    #5 0x56341eddaf28 in Flameshot::config() /home/jeremy/github/flameshot/src/core/flameshot.cpp:221
    #6 0x56341ed40d70 in main /home/jeremy/github/flameshot/src/main.cpp:533
    #7 0x7fa833c2928f  (/usr/lib/libc.so.6+0x2928f)
    #8 0x7fa833c29349 in __libc_start_main (/usr/lib/libc.so.6+0x29349)
    #9 0x56341ed42b94 in _start (/home/jeremy/github/flameshot/build/src/flameshot+0xacb94)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/jeremy/github/flameshot/src/utils/confighandler.cpp:461 in ConfigHandler::value(QString const&) const
==35834==ABORTING

```
</details>

It has to do with the way the config macro's work, not anything user facing. If a user has a typo in their config file a segfault should not occur.

**Comment by Alaskra** [comment]
https://github.com/flameshot-org/flameshot/blob/fbb6d2d7a19775935eafeec073f8e482d9c20e56/flameshot.example.ini#L75-L76
Maybe here also have to change.
ps: Some options are missing in this file, such as showMagnifier, checkForUpdates.

**Comment by cavivie** [comment]
@borgmanJeremy @mmahmoudian @Alaskra I found the reason:
a code bug here, please go to https://github.com/flameshot-org/flameshot/issues/2842

**Comment by cavivie** [comment]
On my local macOS machine, I fixed it, it does work well after fixed.

**Pull request merged**
