### PR TITLE
Fix UI scaling issue in Plasma DE

### PR DESCRIPTION
**Pull request by Mart-Bogdan**
Fixes for issues lupoDharkael/flameshot#564 , lupoDharkael/flameshot#265 and lupoDharkael/flameshot#650.

Possibly laso works for lupoDharkael/flameshot#227  I don't know how to reproduce mixed DPI screen. Need to be tested by Issue opener.

Real laptop screen:

Not fixed flameshot version:

Fixed flameshot version:
3_fixed

Tested on scaling  factor 1.1x

### CODE REVIEW

**Comment by Mart-Bogdan** [comment]
AppVeyor is failing due to SSL issue :-)

```
Command "curl --upload-file ./flameshot_0.6.0_win_X64.zip https://transfer.sh/flameshot_0.6.0_win_X64.zip" failed with exit code 56. Retrying 2 of 3
```

**Comment by Mart-Bogdan** [comment]
My bad. It displays correctly, but the copied value to the clipboard is incorrect, I'll work more on it.

**Comment by Mart-Bogdan** [comment]
Fixed. now it is copying to clipboard and saving to file correctly.
Checked on KUbuntu.
I wonder how I build it for windows to test it there.

**Comment by Mart-Bogdan** [comment]
Tested, it's not breaking MS Windows

**Comment by ZetaoYang** [comment]
@Mart-Bogdan  Did the testing pass under Wayland?

**Comment by Mart-Bogdan** [comment]
@ZetaoYang have no Idea I do not have Wayland on My machine.

You could test yourself if you please: here are binary build for amd64 https://github.com/Mart-Bogdan/flameshot/releases/tag/tmp-fix-scaling-2

**Comment by suside** [comment]
Unfortunately on Wayland it works exactly the same with and without this fix - it only shows a quarter of the screen https://github.com/lupoDharkael/flameshot/issues/265
Even with all env (un)set https://github.com/lupoDharkael/flameshot/issues/265#issuecomment-405630575

 But since it works for others perhaps it can be merged. :thinking:

**Comment by cfviotti** [comment]
Tried this PR successfully within my setup.

Operating System: KDE neon 5.18 (Ubuntu 18.04)
KDE Plasma Version: 5.18.2
Dual monitor: Full HD laptop screen and a 2k Dell Monitor
Using Xorg with 1.25x scaling factor **for both** monitors.

I can confirm I had the issues reported before when on master, and now with theses changes, they are gone.

**Comment by Cretezy** [comment]
image

This still happening on Gnome 3.34.2 (PopOS/Ubuntu 19.10) with 125% scaling (XOrg)

**Comment by Mart-Bogdan** [comment]
Unfortunately I've noticed that positions of tool buttons are incorrect in case of multiple monitors with this PR, so new bug was introduced, I guess. But I'm unable to dig into it.

**Comment by goremukin** [comment]
It works like a charm. I have a single FHD monitor with 1.25x scaling. But yes, there is something wrong with icons.

Operating System: KDE neon 5.19 (Ubuntu 18.04)
KDE Plasma Version: 5.19.2

**Comment by borgmanJeremy** [comment]
I just tested this out on KDE and it doesnt quite work for me. Also it seems to rely on the left monitor being the primary monitor. I've been independently working on this here: https://github.com/flameshot-org/flameshot/issues/564#issuecomment-727297870

Maybe we can collaborate on a fix.

**Comment by Mart-Bogdan** [comment]
Ok, so now I see that on two monitor setup even witput my patch buttons are missplaced 0_O

image

But I still haven't any time to even look at this code :c  sadly

**Comment by ZurMaD** [comment]
I have 3 monitors and I had no problem for releases 0.6+ on Debian 10

**Comment by Mart-Bogdan** [comment]
@ZurMaD  v 0.9.0  windows 10 two monitors

image


Seems issue is in baseline

**Comment by NanOns** [comment]
https://github.com/Mart-Bogdan/flameshot/releases/tag/tmp-fix-scaling-2

It works in Manjaro KDE 😄, I have 2 monitor,3000*2000,1920*1080.

**Comment by ExpectoPatrom** [comment]
Can you merge it please?

**Comment by borgmanJeremy** [comment]
No it does not work properly in multi monitor setups.

**Comment by Mart-Bogdan** [comment]
I would close this PR as it seems not working as expected. And I didn't have time to look into it, sorry :-(. 

And anyway, app author already pushed some code on top.

**Pull request closed without merging**
