### PR TITLE
rename Imgur API Key to Imgur Application Client ID

### PR DESCRIPTION
**Pull request by thehunmonkgroup**
Per https://github.com/flameshot-org/flameshot/issues/2718

I didn't mess with the translations other than the rename.

### CODE REVIEW

**Comment by mmahmoudian** [comment]
I think the translation should be changed as well. that is it of the scope of this PR, but I think the translations should be wiped so that the get redone by the community

**Comment by thehunmonkgroup** [comment]
I did change the existing English versions of the phrase, but feel
completely unqualified to actually translate the term in other languages.

I don't think that should hold up this PR, as it looks like quite a bit of
the translation for that phrase is still incomplete.

**Comment by thehunmonkgroup** [comment]
Makes sense. I'd still vote that removal should be a separate PR, just to keep it clean.

**Comment by borgmanJeremy** [comment]
In general we should NOT refresh the .ts files, but ill merge this as is.

**Pull request merged**
