### PR TITLE
V0.10.2

### PR DESCRIPTION
**Pull request by borgmanJeremy**

### CODE REVIEW

**Comment by borgmanJeremy** [comment]
@ZetaoYang Do you have any ideas how to get this to package from the maintenance branch?

**Comment by ZetaoYang** [comment]
Currently, it is indeed packaged from the maintenance branch.
image
image

**Comment by the-spyke** [comment]
Snap 0.10.2 is still unavailable on the store.

**Comment by borgmanJeremy** [comment]
I cannot figure out how to get snapcraft to pull from a maintenance branch.

**Pull request closed without merging**
