### PR TITLE
Added ability to copy version info

### PR DESCRIPTION
**Pull request by borgmanJeremy**

### CODE REVIEW

**Comment by borgmanJeremy** [comment]
Closes #1732

**Comment by hosiet** [comment]
Code looks OK, but I'm curious about the implementation choice. Why not make the version string selectable by users so that users can copy it by themselves? That would avoid messing around with clipboard (again).

**Comment by borgmanJeremy** [comment]
I could do that too, @mmahmoudian suggested this implementation. 

I'm fine with either way.

**Comment by mmahmoudian** [comment]
I actually had a longer plan for this button and thought I start with this. My longer-term plan was to add more info to this button so that users simply press this button and get the info in a unified format we need for debugging in their clipboard. Version is generally the major info we need, but OS, Xorg or Wayland, DE, ...

I know some are not easy to determine (like DE), but we can have some of the info already there.

**Comment by borgmanJeremy** [comment]
We can get many of those things through Qt directly: https://doc.qt.io/qt-5/qsysinfo.html

**Comment by hosiet** [comment]
Including full info might be a good idea. Actually making text selectable (thus can be copied) can coexist with button. They may all be implemented to make the retrieval of sysinfo easier.

**Comment by mmahmoudian** [comment]
Then @borgmanJeremy how about make the text selectable and for now have the button put some minimal info (eg. Version & OS) in the clipboard? Would that be easy and fast?

**Comment by borgmanJeremy** [comment]
Yup I can do that tonight.

**Comment by borgmanJeremy** [comment]
@mmahmoudian give the latest build a try and let me know if you think of more to be added before merging.

**Comment by mmahmoudian** [comment]
image

The OS is not copied though

**Pull request merged**
