### PR TITLE
fix: ensure --version outputs v0.10.2 for v0.10.2

### PR DESCRIPTION
**Pull request by johnrichardrinehart**
See #2159

### CODE REVIEW

**Review by borgmanJeremy — APPROVED** [review]

**Comment by johnrichardrinehart** [comment]
I think we're all good. Can we get this in and push a new tag?

**Comment by borgmanJeremy** [comment]
I'm not sure why the CI keeps failing

**Comment by johnrichardrinehart** [comment]
@borgmanJeremy It looks like some output is not at the expected path. Is my PR affecting the location of a build output?

https://github.com/flameshot-org/flameshot/runs/4586743050?check_suite_focus=true

**Comment by borgmanJeremy** [comment]
Sorry ive been spending all my time getting version 11 ready. I appreciate you trying to fix this, but I can't sink anytime into fixing the CI or doing a new release for 10.2 when version 11 will make this problem go away.

I should have the beta out today or tomorrow. Almost done writing release notes.

**Comment by johnrichardrinehart** [comment]
Haha, not too bothered. I was just trying to fix the persistent pop-up prompting me to update. Good luck wrapping up the next version!

**Pull request closed without merging**
