### PR TITLE
widgets: capture: consider device scale when resizing widget

### PR DESCRIPTION
**Pull request by M1cha**

### CODE REVIEW

**Comment by borgmanJeremy** [comment]
Awesome I'll get this tested today.

Did you do your testing in wayland or x?

**Comment by M1cha** [comment]
I did this on X(1.20.9.r21.g5c400cae1-2)

**Comment by borgmanJeremy** [comment]
@M1cha Can you post the before and after pictures and more details on your setup? It does not seem to resolve the issue I am thinking of.

**Comment by borgmanJeremy** [comment]
@M1cha Can you follow up on what this fixes?

**Comment by M1cha** [comment]
well for me it fixes the issue I described in detail in #1162
I also posted screenshots there. After this fix it looks just as expected.

**Comment by borgmanJeremy** [comment]
@M1cha Sorry I missed this message! So you can see in my screenshot its not fixing the offset issue for me so I am trying to figure out what the difference is.

**Comment by M1cha** [comment]
@borgmanJeremy if you start flameshot from the console after removing the QT scale, does the issue go away for you? I wanna make sure we're talking about the same problem here:
```
unset QT_SCREEN_SCALE_FACTORS
unset QT_AUTO_SCREEN_SCALE_FACTOR
flameshot
```

**Comment by M1cha** [comment]
the code has conflicts now and I'm not interested in working it anymore.

**Pull request closed without merging**
