### PR TITLE
change arrow tool style

### PR DESCRIPTION
**Pull request by yutent**
Use a nicer looking arrow tool instead. And it resizes automatically.

image

### CODE REVIEW

**Comment by mmahmoudian** [comment]
Surprisingly enough someone else just made the same change (#2826) just 3 days ago!

I have two major criticism:
1. Please never ever write comments in any language other than English
2. As I also told the other developer in the other PR, such changes should be discussed first openly and publicly. This way maintainers of the project will have the opportunity to discuss the design

There have been some discussions about design of arrows that you might be interested to follow:
- #2057
- #2144
- #1960
- #1552
- https://github.com/flameshot-org/flameshot/issues/1487#issuecomment-800941659

and also checkout:
- #1977

**Comment by yutent** [comment]
> Surprisingly enough someone else just made the same change (#2826) just 3 days ago!
> 
> I have two major criticism:
> 
> 1. Please never ever write comments in any language other than English
> 2. As I also told the other developer in the other PR, such changes should be discussed first openly and publicly. This way maintainers of the project will have the opportunity to discuss the design
> 
> There have been some discussions about design of arrows that you might be interested to follow:
> 
> * [Allow create arrows with curved lines. #2057](https://github.com/flameshot-org/flameshot/issues/2057)
> * [Setting to draw arrows pointer first #2144](https://github.com/flameshot-org/flameshot/issues/2144)
> * [Nicer Arrow Tool #1960](https://github.com/flameshot-org/flameshot/issues/1960)
> * [New feature requested: distance labeling arrow #1552](https://github.com/flameshot-org/flameshot/issues/1552)
> * [[Feature request] Some ideas, to be discussed #1487 (comment)](https://github.com/flameshot-org/flameshot/issues/1487#issuecomment-800941659)
> 
> and also checkout:
> 
> * [Add alternative functions for various tools #1977](https://github.com/flameshot-org/flameshot/issues/1977)

既然不愿意就那就关了吧, 我将永远不会再给这个项目任何PR.
另外, 用中文没什么不好, 看不懂可以使用谷歌实时翻译, 正如看不懂英文的其他用户一样.

**Comment by yutent** [comment]
@jack9603301 谁稀罕你啊, 还批评建议。你以为你是救世主啊, 还是白莲花啊。
我就喜欢中文, 你有意见么

**Comment by yutent** [comment]
@jack9603301 你以为你是谁啊, 还要qq。怎么不上天啊。

**Comment by yutent** [comment]
@jack9603301 我贡献不贡献又关你屁事啊

**Comment by yutent** [comment]
@jack9603301 说的好我像很在意那什么狗屁开源人的名头一样。同意就合并, 不同意我就不再pr。
都关闭了几百年的pr, 还追上来 站在道德制高点在那里BBB. 搞的好像全世界都要围着你一样。

**Comment by yutent** [comment]
@jack9603301 说的好像谁有兴趣跟你讨论似的

**Comment by mmahmoudian** [comment]
Ok, seems I'm too late to the party, I should have stamped GTFO on his forehead before this getting to this stage.

@yutent and all his kind will be banned. Zero tolerance policy.

@yutent  用你最懂的语言：开源社区不适合像你这样固执的人。 另外，感谢您向世界展示您丰富的文化。(open source community is no place for bigoted people like you. Also, thank you for showing your rich culture to the world.)

**Pull request closed without merging**
