### PR TITLE
added wayland XCB hack for clipboard

### LINKED ISSUE #1245: flameshot 'copy the selection into the clipboard' function in Fedora 33
**1. Copy the selection into the clipboard.**

**2. Paste into GIMP or Telegram , the image show like:**

**3.  The `Copy the selection into the clipboard` function is available after removing the 'qt5-qtwayland' package.**

- **Flameshot version**
```
$ flameshot --version
Flameshot v0.8.5
Compiled with Qt 5.15.1
```

- **Describe the bug**
Not a bug, maybe need to specify an environment variable to re-render or something.

- **To Reproduce**
```
sudo dnf install qt5-qtwayland
sudo dnf remove qt5-qtwayland
After removing  qt5-qtwayland, the pasted image looks correct.
```

- **System Information**
OS Name: Fedora 33 64-bit
GNOME Version 3.38.2
Windows System Wayland
kernel-5.10.8-200.fc33.x86_64

Thanks!

### PR DESCRIPTION
**Pull request by borgmanJeremy**
Fixes #1245

### CODE REVIEW

**Comment by ZetaoYang** [comment]
Qt 5.15.2 should be fixed. https://bugreports.qt.io/browse/QTBUG-88293

**Comment by borgmanJeremy** [comment]
I tried 5.15.2 on fedora 33 and it didn't seem to work.

**Comment by sincorchetes** [comment]
No support screenshot yet in Fedora 34 with Wayland.

**Comment by darkblaze69** [comment]
Please consider revert this commit. It should be up to user to apply such env variables (QT_QPA_PLATFORM). For long time I wondered why I cannot launch flameshot in native Wayland on GNOME by setting QT_QPA_PLATFORM=wayland because of this dirty hack.

**Pull request merged**
