### PR TITLE
[DRAFT] testing windows ci

### PR DESCRIPTION
**Pull request by borgmanJeremy**

### CODE REVIEW

**Comment by borgmanJeremy** [comment]
@ZetaoYang Can you take a look at this for preliminary windows CI? It still needs to upload the binary but this lets us do everything on github actions without appveyor.

**Comment by borgmanJeremy** [comment]
I think we can use CPack to package it, but don't have a windows machine to test on .

**Comment by ZetaoYang** [comment]
There are many options to build installers for Windows platforms, such as Inno Setup, Qt installation framework.

**Comment by ZetaoYang** [comment]
@borgmanJeremy  The reason for the packaging failure is that the network request timed out when pulling the docker image.

**Pull request merged**
