### PR TITLE
ci: Add support for Ubuntu 24.04

### PR DESCRIPTION
**Pull request by rasa**
Dependent on https://github.com/flameshot-org/flameshot-dockerfiles/pull/3

https://github.com/flameshot-org/flameshot-dockerfiles/pull/3 has been merged, so this PR is ready to be merged too.

Fixes https://github.com/wimpysworld/deb-get/issues/1144

### CODE REVIEW

**Comment by mmahmoudian** [comment]
@holazt do you approve this change as well?

**Comment by holazt** [comment]
this depends on https://github.com/flameshot-org/packpack/pull/6, after it is merged, this can be merged.

**Comment by mmahmoudian** [comment]
@holazt I believe you have the permissions to merge. Please proceed

**Comment by holazt** [comment]
> @holazt I believe you have the permissions to merge. Please proceed as you wish, or let me know what I can do to help

@mmahmoudian Sorry, I have no permission to merge this PR. Besides, Could you help to merge this PR https://github.com/flameshot-org/packpack/pull/7 too?

**Comment by holazt** [comment]
The building https://github.com/flameshot-org/flameshot/actions/runs/10150062277/job/28066335693?pr=3678 for opensuse leap 15.6 is failed, I think it's better to separate RPM spec file `/packaging/rpm/flameshot.spec` into two files, one is for fedora/rehl, another is for opensuse leap, I'll raise a new PR which will cover this PR features and fix what I mentioned issue.

**Comment by mmahmoudian** [comment]
@rasa thanks for the PR and patience

**Pull request merged**
