### PR TITLE
Added instructions for use on xorg

### PR DESCRIPTION
**Pull request by agus-fshr**
I've had lots of people on Discord ask me how I set up flameshot to be used on wm's with xorg as there was no specific settings section like in Ubuntu. I figured I'd just add some quick and easy steps to the README file :)

### CODE REVIEW

**Comment by mmahmoudian** [comment]
Apart from my comments on your first port, aren't these extremely specific to minimal tiling WMs? Gnome, KDE Plasma, Xfce, Mate, Elementry, Solus, and etc. none of which need such instructions.

**Comment by agus-fshr** [comment]
It is useful for anyone who is running on xorg, really. For certain DE's, they might have an option in settings to configure shortcuts and such. This is for anyone who does not have that specific menu in the DE's configuration panel.

**Comment by mmahmoudian** [comment]
>  This is for anyone who does not have that specific menu in the DE's configuration panel.

I don't know of any DE that does not come with one. WMs, esp. the tiling ones or minimal ones typically don't have this, but they have their own config style I guess. For instance those that I have tried (i3wm, dwm, Awesomewm) have their own specific way to define a keybinding. I'm not saying that your PR is bad or wrong, I'm saying that to me it feels incomplete as most of the people on X11 have their own specific way to define their keybindings. Therefore, we should be more specific on who is the intended audience for these instructions.

> what first port?

Sorry for the typo, "port" -> "point" : "Apart from my comments on your first **point**"

> This is my first pull request/comment at all on this repo 

Thank you, contributions are always welcome.

**Comment by agus-fshr** [comment]
@mmahmoudian Yeah, no problem! Thanks for pointing out how to make the PR a bit more meaningful. I'll definitely make a new `.md` for the X11 WM's. :)

**Comment by Creator54** [comment]
> I've had lots of people on Discord ask me how I set up flameshot to be used on wm's with xorg as there was no specific settings section like in Ubuntu. I figured I'd just add some quick and easy steps to the README file :)

I used to use this previously and it caused #2654 for me on dwm, removing it from my xinitrc solved it.

**Comment by borgmanJeremy** [comment]
I agree with @mmahmoudian  suggestions that this be tailored to minimal DE's and not just X11 in general. If you still want to make those changes ill re-open this and merge it.

**Comment by mmahmoudian** [comment]
Perhaps these can be also added in a page on our website when that `.md` is ready

**Pull request closed without merging**
