### PR TITLE
data/debian: Prepare for 0.8.0 release

### PR DESCRIPTION
**Pull request by hosiet**
Files under data/debian/ directory are updated to be prepared for flameshot 0.8.0 release.

### CODE REVIEW

**Comment by ZetaoYang** [comment]
@hosiet I recommend `hicolor-icon-theme` as dependency, it's the default fallback theme used by implementations of the Freedesktop.org Icon Theme specification.

**Comment by hosiet** [comment]
@ZetaoYang  I assumed that anyone with a proper desktop environment installed should have hicolor-icon-theme installed, especially since GTK2 and GTK3 in deb-based distributions depend on it already. But since flameshot is qt-based, adding such dependency should be harmless. Now updated.

**Comment by borgmanJeremy** [comment]
@hosiet Is it safe to merge this now or should it wait until 0.8 is ready to drop?

**Comment by hosiet** [comment]
It should be safe; I don't expect issues with early merge.

**Pull request merged**
