### PR TITLE
Qt6

### PR DESCRIPTION
**Pull request by borgmanJeremy**

### CODE REVIEW

**Comment by AkechiShiro** [comment]
Hi @borgmanJeremy did you abandon this PR or you will still work on it in the future ?

**Comment by borgmanJeremy** [comment]
I've had to step away from working on this so I'll mark it abandoned

**Comment by AkechiShiro** [comment]
Thanks for your efforts ! Could you still leave it open ? Maybe someone else will step in and take it from what you've worked on ?

I'm not sure if we could have the Flameshot maintainer's feedback on this matter.

**Comment by AkechiShiro** [comment]
Any input @rbatinov @AlexP11223 @OrkunTokdemir @MakarenkoPavel @DaraghD @veracioux (just tagging some last committers, not sure if you are maintainers of flameshot but would you have any feedback on this PR ?)

**Comment by rbatinov** [comment]
I am not a maintainer, just edited minor things in the documentation.

**Comment by DaraghD** [comment]
I am also not maintainer, but I dont think a pr this big will get merged anyway. Flameshot works well and going to qt6 wont achieve anything afaik.

**Comment by mmahmoudian** [comment]
@AkechiShiro I'm one of the current maintainers. Anyone who wants to continue the work can easily do so regardless of this PR being open or not.

Migrating to Qt6 is a major change (wish I was skilled enough to do it) which the project have to go through. It is just a matter of time 8and free time of the skilled devs)

**Comment by ReillyBrogan** [comment]
> I am also not maintainer, but I dont think a pr this big will get merged anyway. Flameshot works well and going to qt6 wont achieve anything afaik.

The Qt5 end-of-life is May 2025, and distributions will likely begin the process of removing packages that haven't updated to Qt6 from their repos at that time. Ubuntu in particular is planning on removing all Qt5 packages by the 26.04 LTS ([ref](https://www.phoronix.com/news/Ubuntu-Hopes-Removing-Qt-5)). Moving to Qt6 sooner is better than scrambling once the Qt5 development packages start being removed.

And Qt6 has numerous benefits, including better hidpi support, better rendering performance, and better cmake integration. Saying it won't benefit flameshot is quite ignorant TBH.

**Review by guyueshui — APPROVED** [review]

**Review by guyueshui — APPROVED** [review]

**Comment by AkechiShiro** [comment]
@guyueshui will this change be merged ?? Have they been tested/reviewed ?

**Comment by guyueshui** [comment]
> @guyueshui will these change be merged ?? Have they been tested/reviewed ?

Sorry, I'm not the member of this project. I just clicked the button by curiousity then found it can't be revoked. 😥

**Comment by mmahmoudian** [comment]
@AkechiShiro 
The idea was to have this PR as a testing bed and eventually merged, but unfortunately Jeremy stepped away and none of the other devs picked it up. I would rather have this open, but I also respect Jeremy's decision on closing the PR.

I myself am jot a seasoned C++ developer and I fo triage and community management in this project, so I cannot speak on behalf of other devs whether/when this will be worked on. That said, if you are willing to contribute to the project, any contribution is warmly welcome qnd appreciated. :)

**Pull request closed without merging**
