### PR TITLE
Removed hardcoded binary path

### PR DESCRIPTION
**Pull request by xvitaly**
Removed hardcoded binary path.

Some distributions or package formats does not uses `/usr/bin` at all.

### CODE REVIEW

**Comment by borgmanJeremy** [comment]
Hardcoding the binary path was actually required to make it work with KDE Wayland. 

https://github.com/flameshot-org/flameshot/pull/1603/files

**Comment by xvitaly** [comment]
Then you should use cmake_configure_file() instead of hardcoding paths. It will stop working in Flatpak now.

**Comment by borgmanJeremy** [comment]
Yeah we can put either a configuration in cmake or simply sed the file in the CI. Feel free to submit a new PR that does this.

**Comment by xvitaly** [comment]
> Yeah we can put either a configuration in cmake or simply sed the file in the CI. Feel free to submit a new PR that does this.

Are you sure that hardcoded path matters? I think that `X-KDE-DBUS-Restricted-Interfaces=org.kde.kwin.Screenshot` is enough.

**Comment by borgmanJeremy** [comment]
I can test it again, but I think we had some back and forth on it and it was determined both was needed.

**Pull request closed without merging**
