### PR TITLE
Capture tool button looks at copy on double-click config setting and …

### PR DESCRIPTION
**Pull request by dsticks**
…sets button description accordingly.

Checks to see if "Copy on double click" is checked in config -> General, then changes the button pop-up description to add "or Left Double-Click" if the config is checked.

### CODE REVIEW

**Comment by dsticks** [comment]
Created associated Issue #2807 for this fix.

**Comment by mmahmoudian** [comment]
@dsticks Thanks, well spotted 👍🏼

**Comment by mmahmoudian** [comment]
Please run `clang-format -i $(git ls-files "*.cpp" "*.h")` to format the code properly, and then add it as a commit

**Comment by borgmanJeremy** [comment]
Thanks!

**Comment by dsticks** [comment]
@mmahmoudian I ran clang-format, just on the file I changed.

**Pull request merged**
