### PR TITLE
Improve order and descriptions of Settings/General items

### PR DESCRIPTION
**Pull request by mikkovedru**

### CODE REVIEW

**Comment by mmahmoudian** [comment]
Thanked looks more logical. Would you pleas fix the clang-format

**Comment by borgmanJeremy** [comment]
Generally on board with this change. I agree the whole config widget need's revamped. This is planned as part of the migratino to .ui files, I just dont have a clear vision for what it should look like.

**Comment by borgmanJeremy** [comment]
Can you fix merge conflicts and then I'll merge this next?

**Comment by mikkovedru** [comment]
@borgmanJeremy 
Done.

**Review by borgmanJeremy — APPROVED** [review]

**Comment by borgmanJeremy** [comment]
Thanks!

**Pull request merged**
