### PR TITLE
Add Spanish translation

### PR DESCRIPTION
**Pull request by joseluisq**

### CODE REVIEW

**Comment by luzpaz** [comment]
@joseluisq do you mind rebasing? not sure why appveyor is failing

**Comment by joseluisq** [comment]
@luzpaz no problem.

Only your Windows x86 build is failing:

```sh
Files read from disk: 43
Archive size: 30966138 bytes (30 MiB)
Everything is Ok
appveyor-retry curl --upload-file ./flameshot_%flameshot_version%_win_%PLATFORM%.zip https://transfer.sh/flameshot_%flameshot_version%_win_%PLATFORM%.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0curl: (7) Failed to connect to transfer.sh port 443: Timed out
Command "curl --upload-file ./flameshot_0.6.0_win_x86.zip https://transfer.sh/flameshot_0.6.0_win_x86.zip" failed with exit code 7. Retrying 2 of 3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0curl: (7) Failed to connect to transfer.sh port 443: Timed out
Command "curl --upload-file ./flameshot_0.6.0_win_x86.zip https://transfer.sh/flameshot_0.6.0_win_x86.zip" failed with exit code 7. Retrying 3 of 3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0curl: (7) Failed to connect to transfer.sh port 443: Timed out
Sorry, we tried running command for 3 times and all attempts were unsuccessful!
Command exited with code 7
```

Otherwise try to trigger a rebuild process manually.

**Comment by TheLaluka** [comment]
transfer.sh was down for a couple weeks a while ago, it's up again, can one maintainer restart the test ? It should pass as it's a minor change :pray:

**Comment by joseluisq** [comment]
Any update on this?

**Comment by joseluisq** [comment]
Just a hint. Because [transfer.sh](https://transfer.sh) is dead. It could consider to try other option like https://0x0.st/ or something else.

**Pull request merged**
