### PR TITLE
Reduce dependence on D-Bus

### LINKED ISSUE #1292: Question: how would put flags on the executable for MacOS
I would like to pass the -r flag to the application. For example, how would i perform `flameshot gui -r | python3 file.py` to the flameshot app in MacOS.

Thanks in advance!

### LINKED ISSUE #1480: Run without background process when -r or -p is passed (also allows not using dbus)
Flameshot currently requires starting a separate background process, with the rationale that this is required to handle the clipboard.
Currently flameshot is the only screenshot application that I was able to find, that works on gnome3 with wayland. `gnome-screenshot` doesn't do what I want, so I **need** to use flameshot.

I want to output a screenshot on stdout, and this is possible with the -r option, however, needing to run a background process for `flameshot gui` to work, is awkward.

`flameshot gui` starting a proper flameshot process, taking a screenshot, and then returning the output, is the desired behaviour.
Having this all done in one process context would also allow flameshot to work properly without dbus.

My current solution is this awkward mess:
```
set +m; mkfifo wat; { ( flameshot & flame_pid="$!" ; cat wat; kill -9 "$flame_pid" ) & sleep 5 } 2>/dev/null; flameshot gui -r | display `#do stuff here`; echo > wat; rm wat; set -m;
```
which could be reduced to:
```
flameshot gui -r | display `#do stuff here`
```

https://github.com/flameshot-org/flameshot/issues/1468#issuecomment-799966502 is related to making this process less awkward as well.

### LINKED ISSUE #1579: CLI arguments doesn't work in Mac OS
**Flameshot version**
v.0.9.0

**Describe the bug**
CLI argument doesn't work in the mac os, as in Linux. So I cannot bind the shortcut to make screenshots. Also, as you cannot launch config from CLI, if you disabled the tray icon in the bar, you are actually trapped and need to find the config file to make flameshot usable again.

**To Reproduce**
1. `cd /Applications/flameshot.app/Contents/MacOS/`
2. `./flameshot config` or `./flameshot gui`

**Expected behavior**
Have the same behavior as in Linux

**System Information**
MacOS Big Sur Version 11.2.3

### LINKED ISSUE #1673: Unable to capture screen started using first launch of `flameshot gui` command on Sway
**Flameshot version**
v0.10.0
r1355.35a6d430-1

**Describe the bug**
on starting flameshot with `flameshot` command it works normally as it should do, but when used `flameshot gui` (Flameshot shouldn't be running already), it doesn't work and says unable to capture the screen + there's no icon of flameshot in the system tray.

Here's the preview of the issue mentioned (tested on my Arch Linux - 5.12.11-zen1-1-zen, Sway).

https://user-images.githubusercontent.com/56875929/122627800-8d28c880-d0cf-11eb-8aa3-33867da6e96d.mp4

**To Reproduce**
1. Use sway, waybar(to check system tray icon not showing)
2. export QT_QPA_PLATFORM=wayland
3. now just start flameshot using just `flameshot` command
4. try to capture screenshot using `flameshot gui`, it'll work now !
5. end the process after checking that it works (ctrl + C)
6. `pkill flameshot` just for surety that no instance of flameshot is running
7. now start flameshot with `flameshot gui` command and try to capture screenshot.

**Expected behavior**
I Expected to work it on starting even with flameshot gui + it doesn't look good having no icon in system tray of waybar when started with `flameshot` command only.

**System Information**
Arch Linux - 5.12.11-zen1-1-zen, Sway

### LINKED ISSUE #1716: Allow flameshot to work in a "one off mode"
**TLDR:** Expose one (or two?) settings to automatically open the flameshot UI on launch (basically a setting for `flameshot gui`) and close flameshot after the screenshot has been taken.

**Explanation:**
Windows and GNOME screenshot tools work like this:
1. **Clicking the app launcher starts the app window to take screenshots**
2. Click the take screenshot button to initiate a screenshot
3. Select the region
4. Screenshot is taken
5. **Screenshot app is closed**

Flameshot is superior in functionality and UI. I like that it doesn't open a window where you first have to click an extra button in order to take a screenshot like the other apps I've mentioned above. However using the systray icon in order to trigger a screenshot requires more work then clicking a pinned app launcher icon (1 click for systray + mouse movement + 1 click for "take a screenshot" VS 1 click on app launcher).

The behaviour I have in mind may best be described as a "one off mode".

1. Click on flameshot app launcher automatically opens the screenshot overlay/ui (flameshot gui -d 200)
2. Use cool flamshot tools and finish your screenshot (for example by copying it)
3. Automatically close flameshot

Is there a chance a PR would be accepted exposing this as an additional setting?

--------------

Side note: I first wanted to comment on https://github.com/flameshot-org/flameshot/issues/1696 but because it has already been closed and my request slightly differs I decided to open a new one. (please forgive me)

### LINKED ISSUE #1771: The "screenshot aborted" should go to stderr
While answering to #1681 I realized that `flameshot gui -r > file.png` would always create the file even if the screenshot is aborted (e.g by pressing <kbd>Esc</kbd>). This is because the error "screenshot aborted" is always written to stdout instead of stderr (although the exit code 1 is produced afterwards). I propose writing the errors to stderr.

### LINKED ISSUE #1872: Flameshot can't reopen after quit application on Mac
Flameshot cant reopen after quit application on Mac, when i tried to running from terminal `/Applications/flameshot.app/Contents/MacOS/.flameshot`

``` bash
SingleApplication: Unable to create block.
SingleApplication:  7 "QSharedMemory::create: out of resources"
````

Mac OS version: Big Sur 11.3.2 Apple M1

### PR DESCRIPTION
**Pull request by veracioux**
Closes #1292.
Closes #1480.
Closes #1579.
Closes #1716.
As a side effect: Closes #1771.
May fix #1872.
May fix #1673.
My gut instinct says that this could be involved with #1246 somehow.

**NOTE: I tested nothing on a Mac**
### Terminology
- Daemon - The instance of flameshot that runs in the background
- Daemon hosting - The act of running the daemon in order to support some persistent phenomenon (pinned screenshot, clipboard, etc.)

### Things you should know:
- Flameshot does not support CLI arguments on Windows (and possibly Mac, can't test :cry:)
- When you create a pin, the daemon will host it. If it is not running
- The clipboard gets lost once flameshot quits on X11. Because of this, when any subcommand copies something to the clipboard, the daemon will be asked to host it. Will have to change this behavior for Windows and Mac.
- If there is no need to host something, the daemon will quit automatically.
  I.e. when all pinned widgets are closed, or when the clipboard is changed by another application.

### Changes and TODO (there will be more):
- [X] Pin and clipboard are hosted by the daemon
- [X] `flameshot screen` does not rely on dbus (except for hosting clipboard and pins)
- [X] `flameshot full` does not rely on dbus (...)
- [X] `flameshot gui` does not rely on dbus (...)
- [X] Do not show tray icon in non-dbus commands
- [X] Make `flameshot launcher` independent from dbus
- [X] Make `flameshot config` independent from dbus
- [x] `flameshot launcher` crashes when launching GUI
- [ ] ~Look into addressing #1672 in this~
- [X] "Copy file path after save" does not work properly
- [X] `flameshot gui` mutual exclusivity
- [X] Add option `autoCloseIdleDaemon`, unix-only, default: false
- [X] Tray icon should behave as it did before
- [X] Add the new config options to the GUI
- [ ] Edit test script for MacOS (Jeremy) (https://github.com/flameshot-org/flameshot/pull/2003#issuecomment-951047351)

### TODO (implementation details):
- [x] Reconcile `Controller` and `FlameshotDaemon` - make a clear distinction between them
- [x] Remove unnecessary arguments in Controller::captureTaken(Failed)
- [x] Clean up obsolete code

### TODO (when merging)
- [x] Keep track of notification-clipboard order as in #2053
- [X] Change --print-geometry format after #2013 is merged

### Testing:
- Before testing this PR, make sure the previous daemon version is killed
- **Everything should work as it did before this PR**
- If you have a Windows and/or Mac machine, please test thoroughly. I don't have
  a Mac machine.
- Run the scripts in the `tests` directory inside the repository root. These will test most of the CLI features, but not all!
- Abuse the `screen`, `full` and `gui` subcommands with various options and verify that the daemon is not launched, except when it needs to host the clipboard and/or pinned screenshots. You can use the script `tests/action_options.sh`
- Check if `flameshot gui` works correctly with various options and various types of manual interaction
- Test if stuff is copied to the clipboard correctly, e.g. paste into GitHub/gimp/etc and/or  run `xclip -o -t TARGETS -selection clip`
- If the daemon is not needed, it should quit automatically (on Linux). That is when all pinned screenshot windows are closed and the clipboard gets changed externally. On Windows and Mac, the daemon should keep running.
- Please test the heck out of daemon auto-launching, because this never worked
  on my system for some reason. In other words: make sure to **kill** the daemon before doing the other tests.

### To be discussed

- ~Do we allow multiple instances of `flameshot gui` to run? A benefit of this is the ability to take screenshots of flameshot itself.~
- ~Add a config option to keep daemon running even if not needed??~
- ~What should we do with the system tray if the daemon is running merely to host pins, clipboard, etc?~

### CODE REVIEW

**Comment by veracioux** [comment]
@borgmanJeremy Replying to https://github.com/flameshot-org/flameshot/issues/2054#issuecomment-963691018

It should be now. The only chore that's left to do is to customize the test script for MacOS, but you can do that in a separate PR.

Sorry it took me so long. There was a problem with QSettings when multiple `flameshot gui` instances are running causing an endless loop of file accesses. Took me a long time to debug that.

Right now I'm thinking that we can get rid of DBus altogether. But I'd like to merge this ASAP and leave that for a future PR.

**Comment by borgmanJeremy** [comment]
Ok awesome I'll check it out in a day or so.

I don't think we can ever get rid of dbus entirely as I am not aware of another way to take a screenshot on wayland .

**Comment by borgmanJeremy** [comment]
I made the adjustment to enable MacOS CLI parsing but it seg faults. Need to troubleshoot
image

**Comment by borgmanJeremy** [comment]
It seems to be working today, must have been an OS issue. I have been testing manually but will work on porting the script now. The only issue I have identified so far is the --clipboard option is not working.

**Comment by borgmanJeremy** [comment]
The segfault was fixed with this commit: 58e37b092cdb4bf67ea4ae2a4e04b125fd6beb97

I think all thats left is to fix the test script. @veracioux  is there a reason you send a notification instead of just echoing to the command line?

**Comment by veracioux** [comment]
@borgmanJeremy Thanks, I'll try to merge it tonight.

**Pull request merged**
