### PR TITLE
Change .desktop file to support Plasma Wayland

### LINKED ISSUE #1380: Does not work when using Plasma+Wayland
**Versions**
Flameshot: 5b0bb501dc513f16e93a6d72e06a222a2da6c404
Kwin/Plasma: v5.21
Protocol: Wayland

**Describe the bug**
Flameshot does not take a screenshot. I tried tracking this down with the hopes of creating a patch, but I'm SOL due to my limited knowledge in the Linux desktop space. These are my findings: 

* KWin requires you to use the D-Bus. 
* KWin enforces security by ensuring you have the `X-KDE-DBUS-Restricted-Interfaces` key with the value `org.kde.kwin.Screenshot`.
* KWin uses something called KApplicationTrader to find the desktop file of the process and check if the aforementioned key exists. It compare the `Exec` key in the desktop files and the executable location obtained from procfs to do so.
* Flameshot does not specify the full path to the binary in it's desktop file, unlike Spectacle. 
* Flameshot sets the `X-KDE-DBUS-Restricted-Interfaces` key to `org_kde_kwin_effect-screenshot` instead of `org.kde.kwin.Screenshot`.

I tried setting the `Exec` key full path to the binary as well as changing the `X-KDE-DBUS-Restricted-Interfaces` key to the intended value. However, Flameshot still does not work. I hope someone can fix this issue or help track this down further.

Thanks and sorry if a similar issue already exists.

### PR DESCRIPTION
**Pull request by abhijeetviswa**
Close #1380

### CODE REVIEW

**Comment by abhijeetviswa** [comment]
Well, seems like a path cannot be provided to the Exec key when building an appimage.

**Comment by borgmanJeremy** [comment]
@abhijeetviswa you can edit the github action file to use sed or something to replace the string. As long as the app image still works on KDE wayland, I think this is an okay fix.

**Comment by cossonleo** [comment]
It can not be drag when pin the screenshot.

**Comment by borgmanJeremy** [comment]
Replaced by #1603

**Pull request closed without merging**
