### PR TITLE
Add Dutch translation

### PR DESCRIPTION
**Pull request by ZetaoYang**
- help @pollekepol to submit a PR about translations, see https://github.com/flameshot-org/translation-instruction/issues/5

### CODE REVIEW

**Comment by ZetaoYang** [comment]
This PR flameshot-org/flameshot#440 included Dutch. So I'm confused.

**Comment by pollekepol** [comment]
I understand you are a bit confused. 

Vistaus is a former member of the dutch ubuntu community but is for many
years no longer an active member. 

In the current version of FlamseShot is no Dutch translation present. 

Therefore I made a new translation 

With Regard, Freek Pol (PollekePollewops). 

Ahmed Zetao Yang schreef op 2020-09-10 11:43:

> This PR #440 [1] included Dutch. So I'm confused. 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].
 

Links:
------
[1] https://github.com/flameshot-org/flameshot/pull/440
[2]
https://github.com/flameshot-org/flameshot/pull/881#issuecomment-690117972
[3]

**Comment by ZetaoYang** [comment]
@pollekepol  According to ISO Language Code Table http://www.lingoes.net/en/translator/langcode.htm, there are three suffixes related to the Dutch.
image
Are you mean nl-NL, not nl?

**Comment by pollekepol** [comment]
I'am sorry, it is nl 

But in the po file it was mentioned as de-DE, so i made nl-NL 

Ahmed Zetao Yang schreef op 2020-09-10 12:08:

> @pollekepol [1] According to ISO Language Code Table http://www.lingoes.net/en/translator/langcode.htm, there are three suffixes related to the Dutch.
> [2]
> Are you mean nl-NL, not nl? 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [3], or unsubscribe [4].
 

Links:
------
[1] https://github.com/pollekepol
[2]
https://user-images.githubusercontent.com/10769951/92715575-3cda4880-f390-11ea-990b-3797dc43012c.png
[3]
https://github.com/flameshot-org/flameshot/pull/881#issuecomment-690130841
[4]

**Comment by ZetaoYang** [comment]
@pollekepol Okay I will close this PR. Don't worry, if you feel up to it, you can submit a PR to update nl yourself.

**Pull request closed without merging**
