### PR TITLE
Minor update, PEP8 format and f-string instead of format method

### PR DESCRIPTION
**Pull request by SUPERustam**

### CODE REVIEW

**Comment by SUPERustam** [comment]
Ok

**Comment by SUPERustam** [comment]
> Code from spdlog comes from external project and I believe we shall never change its content, especially for doing code formatting.
> 
> If you would like to contribute to spdlog project, please contact spdlog upstream and forward your contribution there. https://github.com/gabime/spdlog

image
No python files in https://github.com/gabime/spdlog )

**Comment by hosiet** [comment]
Please check the `scripts/` directory. You must have overlooked it.

**Comment by SUPERustam** [comment]
Ah yes! i just look to this :smile::
image

**Pull request closed without merging**
