### PR TITLE
fix: ensure --version outputs v0.10.2 for v0.10.2

### PR DESCRIPTION
**Pull request by johnrichardrinehart**

### CODE REVIEW

**Comment by borgmanJeremy** [comment]
Version 10.2 is a maintance branch only. It does not "exist" on the main branch. It would be very confusing to have to divergent code bases tagged with 10.2.

**Comment by johnrichardrinehart** [comment]
I didn't mean to make the change on `master`. I had _just_ `cherry-pick`ed on top of `v0.10.2` and force-pushed. But, this PR was closed :(  .

**Comment by borgmanJeremy** [comment]
Oh I'm sorry i was sitting at 
my keyboard right when it came in. If the maintaince branch outputs the wrong version that's a defect for sure. Sorry again

**Comment by johnrichardrinehart** [comment]
No problem @borgmanJeremy . I opened #2161 . Please consider it for acceptance :) .

**Pull request closed without merging**
