### PR TITLE
config option to disable grim warrning 

### LINKED ISSUE #3186: Turning off the Flameshot warning
### Flameshot Version

Flameshot v12.1.0 (3ededae5)
Compiled with Qt 5.15.9

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

6.2.13-arch1-1

### Description

I would like a feature where you can turn off the warning, It looks ugly on my screenshots.

### Steps to reproduce

1. run flameshot gui
2. warning shows up 
3. says "flameshot: warning: grim's screenshot component is implemented based on wlroots, it may not be used in GNOME or similar desktop environments" on dunst.

### Screenshots or screen recordings

 https://cdn.discordapp.com/attachments/614906750612668428/1103450673401573396/TYzywxt.png

### System Information

Arch Linux 6.2.13-arch1-1
Dual Monitors, 2K 144hz/1080p 60hz
SwayWM, Wayland

### PR DESCRIPTION
**Pull request by Monirzadeh**
This PR attempts to fix annoying notification about Grim
close #3186
@mmahmoudian Should I add anything else? or any opinions?

### CODE REVIEW

**Comment by mmahmoudian** [comment]
Thanks for the PR. As an internal policy, I generally refrain from merging code changes before it is also approved by other devs. I asked other devs to review this issue on our Matrix channel (which you are also welcome to join). I will also tag them here to increase visibility:

@veracioux @panpuchkov @jack9603301

**Review by jack9603301 — APPROVED** [review]
Thanks to your PR, this PR doesn't seem to have any side effects. Instead, it will no longer output a grim warning message when the user wants to cancel the grim warning. Since this PR does not introduce any by-products, I will agree with this PR change

**Review by jack9603301 — APPROVED** [review]

**Comment by b0ch3nski** [comment]
There is a typo across all the code: `Warnning` -> `Warning`

**Review by jack9603301 — APPROVED** [review]
Well done, since this PR does not introduce any side effects, I will approve it

**Review by mmahmoudian — APPROVED** [review]

**Review by mmahmoudian — APPROVED** [review]

**Comment by mmahmoudian** [comment]
@Monirzadeh thanks for the PR and clean code.
@jack9603301 thanks for the code review.

**Comment by killertofus** [comment]
I still see this 
image


image
dwl, arch flameshot-git

**Comment by killertofus** [comment]
```
[General]
contrastOpacity=188
drawColor=#800000
savePath=/home/killertofus/Pictures
uploadWithoutConfirmation=true

**Comment by killertofus** [comment]
yes @Monirzadeh

**Pull request merged**
