### PR TITLE
Note about potential freezes

### PR DESCRIPTION
**Pull request by hissssst**
I've stumbled across this issue several times, and some of my friends have also experienced this one. This issue was there for several months, so it's time to create a note about it, or think about the compatibility list of WMs and enviroments where flameshot works fine

### CODE REVIEW

**Comment by borgmanJeremy** [comment]
This seems to only happen to users using a DIY distro and that do not properly meet all the flameshot dependencies

**Comment by hissssst** [comment]
@borgmanJeremy , where are these flameshot dependencies stated?

**Comment by hissssst** [comment]
If you're talking about [these ones](https://github.com/flameshot-org/flameshot#dependencies=), than my system meets all the requirements. It's actually not an efficent way to close the discussion before investigating the problem

**Comment by hissssst** [comment]
As I've stated in body of this PR, currently flameshot has no compatibility lists or anything like this.

**Comment by hissssst** [comment]
That's a great idea!

**Comment by mmahmoudian** [comment]
@borgmanJeremy 

> with a list of who to contact 

I'm not sure if I understood this. What do you mean by who to contact? Do you mean that for sway contact Mr. Y and for NixOS contact Ms. X?

**Comment by borgmanJeremy** [comment]
Yes, I'm imagining people sign up to adopt a specific DE or distro. Then if an issue comes in for gentoo for example we can @ that person.

**Comment by mmahmoudian** [comment]
It's good to have such a phone book, but I don't think people would get volunteered for that. Perhaps we can put together such list ourselves based on package maintainers of each distro (at least we know Nix and Gentoo maintainers). But getting such list for DEsis a bit though.

Do you have any approach in mind to attract these people?

**Comment by borgmanJeremy** [comment]
@mmahmoudian nope, I just know that I ignore issues these days for stranger setups and focus on more standards setups.

**Pull request closed without merging**
