### PR TITLE
Circle font color

### PR DESCRIPTION
**Pull request by borgmanJeremy**

### CODE REVIEW

**Comment by borgmanJeremy** [comment]
Closes #941

**Comment by borgmanJeremy** [comment]
Need to change color without QColorConstants. That is not introduced until Qt 5.15

**Review by hosiet — CHANGES_REQUESTED** [review]
I saw you are using Hue value, this must be a typo. We should be looking at Lightness. Otherwise it would be like this:

图片

**Comment by hosiet** [comment]
Besides, this PR mixed with other changes and maybe we can fix it.

**Comment by hosiet** [comment]
This seems to be working, though the threshold can be further adjusted (see those dark blue circles below). Maybe we can merge it for now and tweak the threshold later. The fix for #942 is also working.

图片

**Comment by borgmanJeremy** [comment]
Sounds good. If you find a value that works better feel free to adjust it in a pr.

**Pull request merged**
