### PR TITLE
Add --region option

### LINKED ISSUE #479: Support position and size as input parameter
As others have suggested (#5, #334 and #395) there is no way to capture the current focused window or any window really. Instead you have to use the GUI tool and draw a rectangle yourself.

If I understand the creator correctly they do not want to add this feature if it means that migration to another system suffer because of it.

To solve this, why no introduce new parameters where the user themselves can say what positions and size a window has and then capture that region? With these new parameters a user could easily use another tool to determine the position and size and subsequently Flameshot will support taking screenshots of a window.

I am thinking something like this:
`flameshot capture xPosition yPosition xSize ySize`

Example script (this would get all parameters without any decoration):
```shell
#!/bin/bash

# vars
windowData=$(xdotool getwindowfocus getwindowgeometry)
windowPosData=$(echo $windowData | grep -Eo "[0-9]+,[0-9]+")
windowSizeData=$(echo $windowData | grep -Eo "[0-9]+x[0-9]+")
xPosition=$(echo $windowPosData | cut -d ',' -f 1)
yPosition=$(echo $windowPosData | cut -d ',' -f 2)
xSize=$(echo $windowSizeData | cut -d 'x' -f 1)
ySize=$(echo $windowSizeData | cut -d 'x' -f 2)

# exec
flameshot capture $xPosition $yPosition $xSize $ySize
```

To get decoration info you can tinker with:
`xprop _NET_FRAME_EXTENTS -id $(xdotool getActiveWindow)`

Finally you could bind a keyboard shortcut to the above script and presto, we can now capture the current active window.

### LINKED ISSUE #523: Feature: Select all on GUI start
First, thank you for this application and all the work that has gone into it. Second, just to clarify, this is not a rehash of #324 or #5 

I'm looking to use flameshot in a screen-annotation use case rather than as a pure screenshot program. By that I mean I would like to give some talks/presentations/demonstrations, and in the middle of the presentation I would like to do something akin to:

1. hit print screen to bring up "flameshot gui --select-all"
2. annotate/draw on/mark up my presentation on the screen for emphasis
3. hit esc and continue with the next slide

I know this is getting away from the core purpose of the Flameshot tool, but I think adding an option to the gui startup to select-all would be easier than select-window (see discussion in #5), and could help engender the Flameshot tool to presenters/teachers.

Of course having the pencil tool be automatically selected would be intuitive as well in this use case since there is no need to resize/move the selection box as the entirety of the screen is already selected on start.

Let me know what you think.

### LINKED ISSUE #2010: Add --region option to select an exact screenshot region
**NOTE: This issue is here just so we can track it in milestones.**

### Discussed in https://github.com/flameshot-org/flameshot/discussions/1974

<div type='discussions-op-text'>

<sup>Originally posted by **veracioux** October 14, 2021</sup>
I propose a common solution to the following issues:
- #479
- #523
- #273

(The discussions in the issues became too complicated to follow)

**The problem in a nutshell**

You can't select the whole screen or a specific region without complicated and hacky scripts.

**Proposed solution**

Add a `--region` option to the `gui` and `screen` subcommands. This option can be used in the following ways:
- `--region FORMAT` (see the table below)
- `--region all` (select the entire screen, not available with the `screen` subcommand)
- `--region screen0`, `--region screen1`, etc. (select an entire screen by number, not available with the `screen` subcommand)

| Format | Pros | Cons |
| --- | --- | --- |
| X,Y,W,H | intuitive | non-standard |
| WxH+x+y | used by other CLI tools (xrandr, imagemagick) | may confuse new shell-users (minor IMO) |
| WxH,x,y | N/A | N/A |

\* *x and y are the coordinates of the top-left corner of the region*
\* *w and h are the width and height*

We would also modify the `--print-geometry` to use the format we agree upon (currently uses `W H X Y`). We can even make `--region` accept all of the formats.

:bangbang: Please vote for **one or more** of these formats in the comments below. Please vote even if you are indifferent. :bangbang:

**Other isues that may benefit from this:**
- #334
- #417
- #1509
- #1902

**What I'd like everyone to do**
- If you have other suggestions, post them as comments. We will discuss them, and if they can't be included into the existing proposal, I may ask you to open a new issue.
- Please vote for this post if you agree with the proposal.
- Vote for one of the suggested region formats
- If you prefer someone else's suggestion, vote for it</div>

### PR DESCRIPTION
**Pull request by veracioux**
Closes #479.
Closes #523.
Closes #2010.

Changes & TODO:

- [x] Add --region option to gui subcommand
- [x] Add --region to full
- [x] Add --region to screen
- [x] Allow specifying negative width and height
- [x] Test invalid regions (out of bounds, etc)

### CODE REVIEW

**Comment by borgmanJeremy** [comment]
Does this just need reviewed and tested? Or does more work need completed?

**Comment by veracioux** [comment]
@borgmanJeremy There's not much that can go wrong, but testing is always welcome.

@mmahmoudian I'd like you to test the negative W/H stuff we discussed in #2010.

**Comment by borgmanJeremy** [comment]
Seems to be working well for me after some testing.

**Review by borgmanJeremy — APPROVED** [review]

**Comment by borgmanJeremy** [comment]
@veracioux can you fix the conflicts and then lets get this merged before more conflicts arise.

**Comment by veracioux** [comment]
@borgmanJeremy Yeah. Merging now.

**Comment by nachovizzo** [comment]
Amazing job! Thanks a lot

**Comment by veracioux** [comment]
@nachovizzo My pleasure!

**Pull request merged**
