### PR TITLE
added missing translations

### PR DESCRIPTION
**Pull request by borgmanJeremy**
@mmahmoudian can you test if Persian is properly in this build?

### CODE REVIEW

**Comment by mmahmoudian** [comment]
I tried changing my locale but still majority (99%) of my KDE Plasma is still in English even after logging out and logging back in:

>```
> LANG=fa_IR.UTF-8
> LC_CTYPE=en_US.UTF-8
> LC_NUMERIC=en_US.UTF-8
> LC_TIME=en_US.UTF-8
> LC_COLLATE=en_US.UTF-8
> LC_MONETARY=fi_FI.UTF-8
> LC_MESSAGES=en_US.UTF-8
> LC_PAPER=fi_FI.UTF-8
> LC_NAME=fi_FI.UTF-8
> LC_ADDRESS=fi_FI.UTF-8
> LC_TELEPHONE=fi_FI.UTF-8
> LC_MEASUREMENT=fi_FI.UTF-8
> LC_IDENTIFICATION=fi_FI.UTF-8
> LC_ALL=

I then compiled 63d52c0 and still everything is in English. There is a very high chance that this is my computer's issue. We should perhaps ask @eshagh79 as his computer seems to be setup correctly.

@eshagh79
you can do the following:

```sh
# install things you need to compile
apt install g++ cmake extra-cmake-modules build-essential qt5-default qttools5-dev-tools qttools5-dev libqt5dbus5 libqt5network5 libqt5core5a libqt5widgets5 libqt5gui5 libqt5svg5-dev

# create a temporary folder for this test
mkdir -p ~/tmp
cd ~/tmp

# clone this specific branch
git clone -b add_missing_translations https://github.com/flameshot-org/flameshot.git

clang-format -i $(git ls-files "*.cpp" "*.h")

# compiling (would take about 1 minute)...
mkdir build
cd build
cmake ../
make -j$(nproc --ignore 1)

# make sure all other instances of Flameshot are closed
pkill flameshot
sleep 1

# run this newly compiled Flameshot
./src/flameshot
```

**Comment by borgmanJeremy** [comment]
@ZetaoYang Do you know why that translation file is not properly packaged? Perhaps an issue with RPM find_lang script?

**Comment by ZetaoYang** [comment]
> @ZetaoYang Do you know why that translation file is not properly packaged? Perhaps an issue with RPM find_lang script?

The `grc` in `internationalization_grc.qm` is in Ancient Greek. `%files -f Internationalization.lang` doesn't seem to find it, so it can be solved by adding a following line,
` %{_datadir}/%{name}/translations/Internationalization_grc.qm`




- https://en.wikipedia.org/wiki/Template:Lang-grc
- https://fedoraproject.org/wiki/PackagingDrafts/find_lang
- https://docs.fedoraproject.org/ro/Fedora_Draft_Documentation/0.1/html/RPM_Guide/ch09s05s07.html

**Comment by eshagh79** [comment]
Hello
As Mr. Mahmoudian said, I compiled and ran the flameshot on my own computer, and it displayed the Persian language well.
Of course, not completely, some of the texts were still in English.
I am using Ubuntu 21.10 and it does not have qt5-default package. And the clang-format package was not installed by default and I installed it manually.
And I executed the rest of the commands in the same order as above.

**Comment by mmahmoudian** [comment]
> some of the texts were still in English

From the screenshots the only texts I see that are not translated are:
- the number for the transparency percentage (I don't know if it can be translated)
- the top two items in the sidebar ("Active tool size" & "Active color")

I haven't checked in weblet if they are translated but as far as I can remember they are not among the terms for translation.

**Comment by eshagh79** [comment]
در وبلیت در زبان فارسی فقط 264 ترجمه وجود دارد ولی د زبان اینگلیسی ۳۸۹ عدد. آیا چیزی اشتباه هست؟

**Comment by mmahmoudian** [comment]
> در وبلیت در زبان فارسی فقط 264 ترجمه وجود دارد ولی د زبان اینگلیسی ۳۸۹ عدد. آیا چیزی اشتباه هست؟

Translation:
On weblet there are only 264 terms for translation in Persian but there are 389 terms in the English one. Is there something wrong?

Response:
I don't know, it should be investigated 
نمیدونم، باید چک کنم

**Comment by mmahmoudian** [comment]
Majority of the languages have 348 strings, but these languages have less
- Bulgarian 264
- Finnish 264
- Galician 264
- Greek Ancient 264
- Hebrew 264
- Indonesian 264
- Persian 264
- Vietnamese 264

**Comment by eshagh79** [comment]
من ترجمه اینگلیسی را به صورت پرونده po دانلود کردم و با ترجمه فارسی ادغام کردم، و در حال ترجمه بقیه رشته‌های ناتمام هستم.
احتمالا بعد از اینکه پرونده ترجمه زبان فارسی رو  بروز رسانی کردید و در وبلیت قرار دادید میتونم ترجمه‌ها رو اضافه کنم.

**Comment by borgmanJeremy** [comment]
Yeah I can stud that easily. Now that it's in the cmake file I can refresh the translations and get them in weblate.

**Pull request merged**
