### PR TITLE
Optimize various SVGs

### PR DESCRIPTION
**Pull request by RiedleroD**
I improved many of the project's SVGs to the best of my abilites - although I left some out, either due to minimal possible improvement or due to massive amounts of work being required.

**Some things I improved**
- file sizes of all SVGs now add up to about 2/3rds of what they were before (0.68%)
  (might be even better after the commits I've pushed after writing this, but I'm too sick to check rn)
- decreased the complexity of several icons in the GUI, making rendering slightly more efficient
- fixed some wonky text rendering with unusual fonts
- fixed some non-compliant SVGs

**Some things I messed up**
- I did not read the contribution guidelines until just now, so I guess only a squash merge can rescue this PR
- commit titles are basically useless as well
- the keyboard SVG was just too much - I did improve it, but there's still a lot of room for improvement (which I'm not willing to put my time into, I don't even know where the SVG is shown)
- Some SVGs that are 'fine' are left out. Some minor compliance issues and non-optimal or empty paths remain.

### CODE REVIEW

**Comment by affirVega** [comment]
Compiled and run, looks like all icons are displayed correctly.
image
image

**Comment by borgmanJeremy** [comment]
Thanks! I'll get this checked out a bit more and then merged. Do you think we should regenerate the png's based on these new svg's?

**Comment by RiedleroD** [comment]
I think regenerating the PNGs won't make any difference. You're free to try, but don't say I wasted your time, @borgmanJeremy  ;P

**Comment by borgmanJeremy** [comment]
We are going to have a beta of V11 soon, probably by the end of the weekend. Do you think this will be ready by then?

**Comment by mmahmoudian** [comment]
> the keyboard SVG was just too much - I did improve it, but there's still a lot of room for improvement (which I'm not willing to put my time into, I don't even know where the SVG is shown)

I think you refer to the picture tgat is shown while setting a keyboard shortcut. In config when changing a keyboard shortcut a windows opens to capture what keys you press and in that windows a keyboard picture is displayed.

**Comment by RiedleroD** [comment]
@borgmanJeremy I think it's already ready… I originally wanted to do the rest too (except for the keyboard one) but I got sick recently & haven't fully recovered. Besides, the rest are mostly fine, just a few standard compliance issues and slightly non-optimal paths. And some empty paths. But nothing major as far as I can see.

@mmahmoudian Yes, that's the one. Thanks! Not sure what purpose it serves though, as it kinda just sits there… Maybe a symbol of a single key would be better there? I can open a PR for that once I feel better.

**Comment by mmahmoudian** [comment]
@RiedleroD I hope you recover soon.

Regarding the current keyboard symbol, I'm not sure if changing it would help, but I'm personally open for suggestions

**Review by borgmanJeremy — APPROVED** [review]

**Comment by borgmanJeremy** [comment]
Thanks!!

**Comment by borgmanJeremy** [comment]
This seems to have broken all the icons on windows so I need to revert it.

**Comment by RiedleroD** [comment]
bruh what the hell

**Comment by mmahmoudian** [comment]
@borgmanJeremy good that you tested it before releasing the v0.11.0 It would have be chaotic in the issues section 😅

**Comment by RiedleroD** [comment]
do you by any chance use an old version of rsvg on windows? I know it has some problems with parsing shorthand numbers in elliptical arcs, so if that could be fixed instead, that'd be cool.

**Comment by borgmanJeremy** [comment]
I'll look into which version I'm using. My windows box is fully up to date and I'm using the latest qt LTS.

**Comment by borgmanJeremy** [comment]
MacOs has the same issue actually.

**Comment by RiedleroD** [comment]
@borgmanJeremy I'm trying to test it rn but I can't compile for windows - there's no compilation documentation for windows in the readme and using the instructions for debian on WSL Ubuntu doesn't work. Logs are attached.

Can't test for MacOS because I don't have OSX at hand, but let's hope it's the same problem on both systems.

[cmake.log.txt](https://github.com/flameshot-org/flameshot/files/7780996/cmake.log.txt)
[make.log.txt](https://github.com/flameshot-org/flameshot/files/7780991/make.log.txt)

**Comment by borgmanJeremy** [comment]
Building on windows is a freaking a pain IMO :)

I usually download the community version of Qt and Qt Creator. Then you can open the project as a CMake project in Qt creator.

**Comment by RiedleroD** [comment]
@borgmanJeremy I can't get it to work... can you please build it on your end and send me the file?

**Comment by borgmanJeremy** [comment]
Every pull request builds all artifacts, so if you submit a PR you can download the artifacts

**Pull request merged**
