### PR TITLE
Cleaned up flatpak build for flathub submission

### PR DESCRIPTION
**Pull request by borgmanJeremy**

### CODE REVIEW

**Comment by borgmanJeremy** [comment]
@ZetaoYang I am not 100% sure why the flatpak build is failing, is this just a temporary failure since the name was changed between what is on master vs this PR?

**Comment by ZetaoYang** [comment]
this https://github.com/flameshot-org/flameshot/blob/master/src/core/controller.cpp#L263 need update too.

**Comment by ZetaoYang** [comment]
this desktop file need update https://github.com/flameshot-org/flameshot/blob/master/.github/workflows/Linux-pack.yml#L341

**Comment by ZetaoYang** [comment]
@borgmanJeremy You can see the source code latest commit id, this PR patch doesn't apply to master branch. 
image

**Pull request merged**
