### PR TITLE
Added screenshot with interval

### PR DESCRIPTION
**Pull request by timurchak**

### CODE REVIEW

**Comment by borgmanJeremy** [comment]
Have you tried setting a delay through the launcher which can be activated from the tray icon?

**Comment by timurchak** [comment]
> Have you tried setting a delay through the launcher which can be activated from the tray icon?

You are absolutely right =)

**Comment by borgmanJeremy** [comment]
Sorry my question was, is there a reason to add this feature since we support delays in the launcher?

**Comment by timurchak** [comment]
@borgmanJeremy Sorry, apparently I didn't see it.  after looking better, found this [discussion](https://github.com/flameshot-org/flameshot/issues/582) and indeed such a function is already there.  Sorry, the pull can be closed =)

**Pull request closed without merging**
