### PR TITLE
Add --clipboard to gui subcommand

### PR DESCRIPTION
**Pull request by veracioux**
Tracks issue #1559.

When you run `flameshot gui --clipboard`, any action that closes the GUI (except for pressing Escape) will copy the screenshot to the clipboard.

This patch currently has a minor problem. If you click copy to clipboard in the GUI, you will get the notification "Capture saved to clipboard" twice - once from the button and once from the `--clipboard` option. Need to figure out a good way to suppress this.

### CODE REVIEW

**Comment by veracioux** [comment]
Done.

**Comment by borgmanJeremy** [comment]
closes #1559

**Review by borgmanJeremy — CHANGES_REQUESTED** [review]
Can you add a help string to describe this feature? 

Should be in /src/main around line 180'ish

**Review by veracioux — COMMENTED** [review]
There is already a help string for the --clipboard option. It is the same as for the other subcommands.

**Review by borgmanJeremy — APPROVED** [review]

**Pull request merged**
