### PR TITLE
Add Clear button (#548)

### PR DESCRIPTION
**Pull request by weishiuchang**
* implement clear button
 * add clear button graphics
 * add button to gui
 * attach delete key to clear button

### CODE REVIEW

**Comment by luzpaz** [comment]
Do all the individual `.ts` needs to be modified? Doesn't just one file get updated and then the rest of the language.ts files are generated from it?

**Comment by WeiShiuChang** [comment]
Sorry - I'm not that familiar with QT5 i18n commands. I ran the command `lupdate-qt5 -verbose flameshot.pro` and those were the changes it made.

**Comment by luzpaz** [comment]
@WeiShiuChang actually that sounds about right. Never mind me.

**Comment by AlexP11223** [comment]
I think currently translations are usually updated in separate PRs, otherwise you will get lots of conflicts.

**Comment by borgmanJeremy** [comment]
Is there a reason to add a clear button now that undo is implemented? IE repeating undo is the same as clear?

**Comment by weishiuchang** [comment]
I personally found use in a clear all, but that's just my own use case. But I'm not fussed either way.

**Comment by AlexP11223** [comment]
> We need to balance new features against complaints that there are too many icons :)

Maybe this icon could be disabled by default.

**Pull request closed without merging**
