### PR TITLE
improve slovak translation

### PR DESCRIPTION
**Pull request by TomasKukumberg**
I've added some missing translations for the slovak language.

### CODE REVIEW

**Comment by borgmanJeremy** [comment]
Thanks for this! However, we use weblate to manage our translations and if I merge a manually translation it will break the weblate workflow. Could you please submit this using weblate?

**Comment by TomasKukumberg** [comment]
Yeah i was suspecting that, is there any tutorial how to submit from the weblate? I've got all translations saved in translation memory but i can't seem to find a way to submit them.

**Comment by borgmanJeremy** [comment]
I havent used the translation memory feature before. When I first set up the project I tested it using the web GUI on weblate.

**Comment by TomasKukumberg** [comment]
Ok, i will check it out, ty.

**Pull request closed without merging**
