### PR TITLE
Make loading of languages consistent across invocation types

### PR DESCRIPTION
**Pull request by veracioux**
Currently, languages are loaded only when invoking flameshot as a daemon, so localization doesn't work for the other invocation types. This fixes that.

### CODE REVIEW

**Comment by veracioux** [comment]
@mmahmoudian Please review it if you can.

**Review by mmahmoudian — APPROVED** [review]
Yeah, logical move 👍 I wonder how much the re-initialization affects the performance.

**Comment by mmahmoudian** [comment]
@veracioux It seems something didn't went well. I'm getting the following:

```console
❯  flameshot gui
QLayout: Attempting to add QLayout "" to SidePanelWidget "", which already has a layout
[1]    275691 segmentation fault (core dumped)  flameshot gui
```

**Comment by mohad12211** [comment]
> @veracioux It seems something didn't went well. I'm getting the following:
> 
> ```
> ❯  flameshot gui
> QLayout: Attempting to add QLayout "" to SidePanelWidget "", which already has a layout
> [1]    275691 segmentation fault (core dumped)  flameshot gui
> ```
> 
> Triggering it from the tray icon works though

any news about this crashing issue?

**Comment by mmahmoudian** [comment]
@mohad12211 unfortunately not resolved yet. Please use clicking on the tray icon which works. This is very high priority and we will resolve it.

**Comment by marceldev89** [comment]
@mmahmoudian made a fix for the crash at https://github.com/flameshot-org/flameshot/pull/3370 :)

**Pull request merged**
