### PR TITLE
Always show post upload actions

### LINKED ISSUE #2312: No 'Save to disk' button visible for Imgur uploads
### Flameshot Version

Flameshot v11.0.0.

### Installation Type

Compiled from source

### Operating System type and version

Linux

### Description

I have cherry-picked commit 00b1088 and applied it to v11.0.0, but there is no 'Save to disk' button visible when I upload the screenshot - all it does is ask for confirmation if the image has to be uploaded, and then a notification appears that the URL has been copied to the clipboard.

@borgmanJeremy has suggested that 'Copy URL after Upload' option has to be unchecked to avail this feature - it indeed works that way. I would like to suggest that this 'Save to disk' option could work despite this workaround, if possible.

Thanks in advance. 

### Steps to reproduce

_No response_

### Screenshots or screen recordings

_No response_

### System Information

CentOS 7.x

### PR DESCRIPTION
**Pull request by borgmanJeremy**
@mmahmoudian are you okay with this change? it closes #2312

### CODE REVIEW

**Comment by mmahmoudian** [comment]
I don't understand the premise of the #2312. Reading changes of this pull request also didn't help me understand what the problem is. I'll try to compile it and see if I can figure it out from the behavior diff

**Comment by borgmanJeremy** [comment]
image
 That screen is only shown if "Copy URL after upload" is disabled in the options.

**Comment by borgmanJeremy** [comment]
@mmahmoudian can you post your config? I want to resolve your seg fault before merging.

**Comment by mmahmoudian** [comment]
@borgmanJeremy 

```ini
[General]
allowMultipleGuiInstances=true
buttons=@Variant(\0\0\0\x7f\0\0\0\vQList<int>\0\0\0\0\x16\0\0\0\0\0\0\0\x1\0\0\0\x2\0\0\0\x3\0\0\0\x4\0\0\0\x5\0\0\0\x6\0\0\0\x12\0\0\0\xf\0\0\0\x16\0\0\0\x13\0\0\0\a\0\0\0\b\0\0\0\t\0\0\0\x10\0\0\0\n\0\0\0\v\0\0\0\r\0\0\0\x17\0\0\0\xe\0\0\0\f\0\0\0\x11)
contrastOpacity=135
copyPathAfterSave=true
disabledTrayIcon=false
drawColor=#ffff00
drawFontSize=7
drawThickness=5
ignoreUpdateToVersion=0.10.2
predefinedColorPaletteLarge=false
savePath=/home/mehrad/Pictures
savePathFixed=false
showMagnifier=false
showStartupLaunchMessage=true
startupLaunch=true
uiColor=#ff7300
undoLimit=100
uploadHistoryMax=0
useJpgForClipboard=false
userColors=picker, #800000, #ff0000, #ffff00, #00ff00, #008000, #00ffff, #0000ff, #ff00ff, #800080, #fa0164

[Shortcuts]
TYPE_ARROW=A
TYPE_CIRCLE=
TYPE_CIRCLECOUNT=
TYPE_COMMIT_CURRENT_TOOL=Ctrl+Return
TYPE_COPY=Ctrl+C
TYPE_DELETE_CURRENT_TOOL=Del
TYPE_DRAWER=D
TYPE_EXIT=Ctrl+Q
TYPE_IMAGEUPLOADER=
TYPE_MARKER=M
TYPE_MOVESELECTION=Ctrl+M
TYPE_MOVE_DOWN=Down
TYPE_MOVE_LEFT=Left
TYPE_MOVE_RIGHT=Right
TYPE_MOVE_UP=Up
TYPE_OPEN_APP=Ctrl+O
TYPE_PENCIL=
TYPE_PIN='
TYPE_PIXELATE=B
TYPE_RECTANGLE=R
TYPE_REDO=Ctrl+Shift+Z
TYPE_RESIZE_DOWN=Shift+Down
TYPE_RESIZE_LEFT=Shift+Left
TYPE_RESIZE_RIGHT=Shift+Right
TYPE_RESIZE_UP=Shift+Up
TYPE_SAVE=Ctrl+S
TYPE_SELECTION=S
TYPE_SELECTIONINDICATOR=
TYPE_SELECT_ALL=Ctrl+A
TYPE_SIZEDECREASE=-
TYPE_SIZEINCREASE=+
TYPE_TEXT=T
TYPE_TOGGLE_PANEL=Space
TYPE_UNDO=Ctrl+Z
```

**Pull request merged**
