### PR TITLE
Fixed crash selecting texttool

### PR DESCRIPTION
**Pull request by AndreaMarangoni**
The `close()` method was aborting the screenshot. I am not sure why only on the `texttool`.
I went for a safer approach which consist on hiding the tool and to avoid any leak I am setting its parent and flagging the widget to `deleteLater()`.

### CODE REVIEW

**Review by borgmanJeremy — APPROVED** [review]

**Comment by borgmanJeremy** [comment]
Thank you! I was struggling to find a fix for this.

**Comment by fuzunspm** [comment]
is this merged with latest release? I'm having the said fixed issue

**Comment by mmahmoudian** [comment]
@fuzunspm No, this is merged on 2022-02-05 and the latest release was published in 2022-01-15:


image

image

**Comment by thraizz** [comment]
Is there a release planned somewhere soon? This happens to me daily, the only way to prevent this is to de-select the text tool before clicking somewhere, when editing text. Huge pain in the bum, if you add multiple texts to a screenshot and then flameshot aborts on the last click...

**Comment by mmahmoudian** [comment]
@thraizz  you can build from source or install from nightly builds:
https://flameshot.org/docs/installation/development-build/

**Pull request merged**
