### PR TITLE
fixing icon regression

### PR DESCRIPTION
**Pull request by borgmanJeremy**

### CODE REVIEW

**Comment by hosiet** [comment]
This looks okay to me, but I have no idea whether this breaks Flathub's requirement. Please double check with that part.

**Comment by borgmanJeremy** [comment]
@hosiet Will do, I'll kick off that build next

**Comment by hosiet** [comment]
One more question: is CMake installing duplicated real image files instead of symlinks? I don't have computers around so please check it. It seems to be the case from CMakeLists.txt (those COPYONLY lines are not installing symlinks at all).

**Comment by borgmanJeremy** [comment]
@hosiet Yes its copying the file twice. It seemed that cmake method did not allow for symlinking. I can manually call to the shell to make the symlink if we want:

https://stackoverflow.com/questions/35765106/symbolic-links-cmake

**Comment by ZetaoYang** [comment]
It is recommended to refer to copyq for this way of handling icon names.

**Comment by borgmanJeremy** [comment]
@ZetaoYang I think that will have the same problem because it will only create a org.flameshot.Flameshot.svg....it also needs a flameshot.svg.

**Comment by borgmanJeremy** [comment]
@ZetaoYang I think that will have the same problem because it will only create a org.flameshot.Flameshot.svg....it also needs a flameshot.svg.

**Comment by xvitaly** [comment]
@borgmanJeremy Do not install duplicates. GNU/Linux maintainers now need to remove them manually.

On Flatpak's side you should use `"rename-icon": "flameshot"`.

**Comment by borgmanJeremy** [comment]
@xvitaly I am symlinking them now. Is that still an issue? If you have a way to only have one icon set work for all the different packages please submit a PR. I am honestly very burned on on working on packaging conflicts and the current solution is working.

**Comment by xvitaly** [comment]
> I am symlinking them now. Is that still an issue?

Yes. 1 icon for 1 application.

> If you have a way to only have one icon set work for all the different packages please submit a PR

You need to revert all Flathub* commits and then use `"rename-icon": "flameshot",` on Flathub's side.

**Comment by borgmanJeremy** [comment]
thanks!

**Comment by xvitaly** [comment]
@borgmanJeremy https://github.com/flameshot-org/flameshot/pull/1057

**Pull request merged**
