### PR TITLE
More accurate Portuguese translation

### PR DESCRIPTION
**Pull request by d4niloArantes**
Nothing big but it kind bothers me.

### CODE REVIEW

**Comment by miguelbrandao** [comment]
As a fellow portuguese speaker, I can say this translation is way better

**Comment by Streppel** [comment]
@lupoDharkael <3

**Comment by mmahmoudian** [comment]
As a headsup, this might conflict with #658 as they both are modifying the same file.

**Comment by borgmanJeremy** [comment]
Fixed merge conflicts on my fork. Will merge in a day or so with other translations.

**Pull request closed without merging**
